name: auto_exporter
description: A Dart package that allows you to auto export files, see README.md to know how to use it, just use the terminal and change the dart file name.
version: 1.4.3
homepage: https://github.com/normidar/auto_exporter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # source_gen: ^1.2.1
  build: ^2.3.1
  build_resolvers: ^2.0.10
  glob: ^2.1.0

dev_dependencies:
  effective_dart: ^1.3.2
  lints: ^1.0.1 # 2.0.0 is in devlop
